### PR TITLE
add solver parameter for solve_model function

### PR DESCRIPTION
**Pull request by MichaelPesce**
## Fixes/Addresses/Summary/Motivation:

The solve_model function automatically detects when gurobi is on a user's machine. This prevents the user from using CBC if they wanted to choose to do so. It also prevents the UI from providing the option for a user to choose which solver to run.

## Changes proposed in this PR:
- Add solver as a parameter to the solve_model function.
- If the parameter is not provided, the function will act the same as it previously did

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Review by melody-shellman — CHANGES_REQUESTED** [review]
Works great - just tested it. For consistency purposes, I'd like to propose that solver selection is added to the options dictionary instead of as a separate input to solve_model like so:

In strategic_produced_water:
```
def solve_model(model, options=None, solver=None):
    if options is None:
        options = {
            "deactivate_slacks": True,
            "scale_model": True,
            "scaling_factor": 1000000,
            "running_time": 60,
            "gap": 0,
        }
    # load pyomo solver
    if "solver" not in options.keys():
        opt = get_solver("gurobi_direct", "gurobi", "cbc")
    else:
        opt = get_solver(options["solver"])
```

**Review by melody-shellman — DISMISSED** [review]
Looks good! thanks for adding this feature :)

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Review by melody-shellman — APPROVED** [review]
looks good!

**Comment by ksbeattie** [comment]
@MAZamarripa can we get you to re-review this?

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Pull request merged**
