### PR TITLE
Operation Model - add RCA arcs

### PR DESCRIPTION
**Pull request by melody-shellman**
## Summary
Input File Changes
1.	Added RCA tab copied from the strategic file
a.	Edit to only include completions sites in the Completions Tab
b.	Change all to 0 so the results stay the same
2.	Edited the "Treatment Sites" tab to contain two treatment sites
3.	Added "Treatment Efficiency" tab

Operational_produced_water_optimization_model.py changes
1.	Line 31: import the “simple_constraint_rule” function
2.	Line 445: add RCA_Table  dictionary for consistency
3.	Line 570-176: add p_RCA parameter
4.	Line 967-972 : add p_epsilon_treatment parameter
5.	Completions Pad Demand Balance Constraint
a.	Issue: Treatment to completion piping arcs are missing in the balance
b.	Edits:
i.	Added Line 1179 (RCA summation)
6.	Network Node Balance Constraint
a.	Issue: Storage to node pipeline is missing
b.	Edits:
i.	Line 1624 (added) SNA summation
c.	Original solution has nothing sent to storage, so this should be unchanged
7.	Treatment Balance Constraint
a.	Issue: missing constraint
b.	Edits:
i.	Added Lines  2332 - 2343 (added): Treatment Balance Rule (copy pasted from the strategic model)
ii.	Note: identical to Treatment Balance Rule from strategic model EXCEPT the “simple_constraint_rule(Treatment Balance Rule)” call. Because the arc sets are all currently empty, the operational model currently errors without this call. 
8.	Completions Reuse Cost Constraint
a.	Issue: missing RCA arc
b.	Edits:
i.	Added Line 2479: RCA summation

Run_operational_model.py changes
1.	Line 29, Line 57: Add “RCA” and “TreatmentEfficiency” to parameter list
2.	Line 63: Adjusted fname to read file in from the correct directory

### CODE REVIEW

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Comment by drouvenm** [comment]
@Andresj89 Is this PR good to go? I believe you had requested changes - but to the best of my knowledge they've been addressed, right?

**Review by Andresj89 — APPROVED** [review]
LGTM

**Comment by Andresj89** [comment]
@drouvenm Markus, this PR is ready to be merged, it just needs one more approval

**Review by drouvenm — APPROVED** [review]

**Pull request merged**
