### PR TITLE
Add case study documentation

### PR DESCRIPTION
**Pull request by tarnold17**
## Fixes/Addresses/Summary/Motivation:

Add initial documentation for case studies.

## Changes proposed in this PR:
- Rename case study input files to be shorter

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Review by drouvenm — APPROVED** [review]
I like this whole page a lot @tarnold17! The table in particular, should be incredibly helpful to new PARETO users (industrial or academic). Coupled with the schematics (including the updated labels), I imagine everyone on the team will benefit from this documentation. Well done!

**Review by melody-shellman — APPROVED** [review]
Looks great! An excellent first pass. If time allows, I thought of another row that would be useful to add - 
Compatible Solvers: CBC (open source), Gurobi (commercial)
I believe all but the treatment demo are compatible with both. Treatment demo requires Gurobi

**Comment by drouvenm** [comment]
@melody-shellman On the note of solver selections, someone needs to show me where/how I can do that for the strategic model. It's so straightforward for the operational model but I didn't even find that option for the strategic run file...

**Comment by tarnold17** [comment]
> @melody-shellman On the note of solver selections, someone needs to show me where/how I can do that for the strategic model. It's so straightforward for the operational model but I didn't even find that option for the strategic run file...

@drouvenm you can select the solver for the strategic model by passing a "solver" option to the `solve_model` function. You are right to notice that we don't do that in `run_strategic_model.py`, so running this script uses the default behavior, which is to use Gurobi, and if it can't find Gurobi, then CBC instead.

**Comment by tarnold17** [comment]
> Looks great! An excellent first pass. If time allows, I thought of another row that would be useful to add - Compatible Solvers: CBC (open source), Gurobi (commercial) I believe all but the treatment demo are compatible with both. Treatment demo requires Gurobi

@melody-shellman I think the issue is not really one of "compatibility", but rather, that CBC just isn't a good enough solver to solve the strategic treatment demo in a reasonable amount of time. However, I think it's possible that there are optimizations/improvements we could make to the strategic model that would allow it to be solved relatively quickly with CBC. So I decided to take your suggestion, but I worded it as Gurobi being "recommended" for the treatment demo.

**Comment by melody-shellman** [comment]
> > Looks great! An excellent first pass. If time allows, I thought of another row that would be useful to add - Compatible Solvers: CBC (open source), Gurobi (commercial) I believe all but the treatment demo are compatible with both. Treatment demo requires Gurobi
> 
> @melody-shellman I think the issue is not really one of "compatibility", but rather, that CBC just isn't a good enough solver to solve the strategic treatment demo in a reasonable amount of time. However, I think it's possible that there are optimizations/improvements we could make to the strategic model that would allow it to be solved relatively quickly with CBC. So I decided to take your suggestion, but I worded it as Gurobi being "recommended" for the treatment demo.

Agreed, the note you have in the latest commit I think is good!

**Review by melody-shellman — APPROVED** [review]
lgtm!

**Pull request merged**
