### PR TITLE
Seismicity updates

### LINKED ISSUE #292: Fix header in "WellPressure" tab for strategic model input files
In all strategic model case studies, the header of the tab "WellPressure" says "Table of Production Rate Forecasts by Pads [bbl/day]". This is obviously incorrect and is probably a result of copy and pasting from either the tab "PadRates" or "FlowbackRates". This header should be fixed to accurately describe the contents of the "WellPressure" tab.

### PR DESCRIPTION
**Pull request by tarnold17**
## Changes proposed in this PR:
- Index disposal capacity increments by individual wells (updated tab: DisposalCapacityIncrements)
- Add tabs to support data required for seismicity risk calculations
    - "SWDDeep"
    - "SWDAveragePressure"
    - "SWDProxOrphanWell"
    - "SWDProxInactiveWell"
    - "SWDProxEQ"
    - "SWDProxFault"
    - "SWDProxHpOrLpWell"
    - "SWDRiskFactors"
- Resolve #292
  
This PR should not be reviewed/merged until after #276 is merged.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Review by ElmiraShamlou — APPROVED** [review]
LGTM

**Review by melody-shellman — COMMENTED** [review]
Generally looks good. I had one comment/question before approving, 
Do we anticipate supporting alternative units for these parameters like we do other parameters in PARETO (particularly the distance units)?  I think it would be nice to do so, but based on current work, it looks like that's not happening yet. 
If so, ideally, it would be nice for the table names to populate according to the selected unit, particularly for the distances like so:
image

**Comment by tarnold17** [comment]
> Generally looks good. I had one comment/question before approving, Do we anticipate supporting alternative units for these parameters like we do other parameters in PARETO (particularly the distance units)? I think it would be nice to do so, but based on current work, it looks like that's not happening yet. If so, ideally, it would be nice for the table names to populate according to the selected unit, particularly for the distances like so: image

@melody-shellman good comment. At present, these parameters assume particular units, and right now there are not plans to support alternate units. That's a feature we could consider adding down the line, but it's not a concern at present.

**Review by melody-shellman — APPROVED** [review]
Approved! Units flexibility to be considered in #290

**Pull request merged**
