### PR TITLE
Pipeline Expansion Cost Revision

### PR DESCRIPTION
**Pull request by tarnold17**
## Fixes/Addresses/Summary/Motivation:

- To prevent water from being piped from treatment sites to nodes, remove the RNA terms from the network node balance (`NetworkNodeBalanceRule`)
- Also remove RNA terms from `BidirectionalFlowRule1`, `BidirectionalFlowRule2` and `NetworkNodeCapacityRule`
- Reformulate `PipelineExpansionCapExDistanceBasedRule` and `PipelineExpansionCapExCapacityBasedRule` to use the universal location set (`s_L`) instead of enumerating all of the different types of arcs
- Update treatment demo input file to remove all RNA arcs
- Update the strategic model documentation and tests accordingly

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by nareshsusarla** [comment]
Please review lines 3135 - 3137, I think they should be removed too.
```
                    + sum(
                        model.v_F_Piped[r, n, t] for r in model.s_R if model.p_RNA[r, n]
                    )

```

In addition, some minor comments are as follows:

1.  Line 2309 - 2316, they look redundant:
```
            elif l in model.s_R and l_tilde in model.s_N:
            if model.p_RNA[l, l_tilde]:
                constraint = (
                    model.vb_y_Flow[l, l_tilde, t] + model.vb_y_Flow[l_tilde, l, t] == 1
                )
                return process_constraint(constraint)
            else:
                return Constraint.Skip

```

2. Same goes with lines: 2467 - 2475:
```
        elif l in model.s_R and l_tilde in model.s_N:
            if model.p_RNA[l, l_tilde]:
                constraint = (
                    model.v_F_Piped[l, l_tilde, t]
                    <= model.vb_y_Flow[l, l_tilde, t] * model.p_M_Flow
                )
                return process_constraint(constraint)
            else:
                return Constraint.Skip

```

Please do a search for RNA arcs in the code and see if anything else is concerning. Thanks

**Comment by tarnold17** [comment]
@nareshsusarla In the latest commit, I have removed the three sections of code that you indicated. I searched through the strategic model code, and here are the remaining spots where I see references to RNA:

- `PipelineCapacityExpansionRule`
- `PipelineCapacityRule`
- `PipingCostRule`
- `TotalPipingCostRule`
- `PipelineExpansionCapExDistanceBasedRule`
- `PipelineExpansionCapExCapacityBasedRule`
- `SlackCostsRule`
- `NetworkNodeWaterQualityRule`

I can remove references to RNA in some of these functions in this PR if you'd like, but my understanding from our meeting last Friday is that we want to save that cleanup for a future PR (I created an issue for that work, see #181).

**Comment by melody-shellman** [comment]
To add to the comment above, this future PR should also remove the RNA tab from the input file.

**Review by melody-shellman — CHANGES_REQUESTED** [review]
If the goal of this PR is to remove RNA arcs from treatment node balances only, I think this PR accomplishes this. 

With the most recent commit, I think the documentation may be missing updates to the bidirectionality constraint, network node constraint, and node capacity constraint?

**Comment by tarnold17** [comment]
> With the most recent commit, I think the documentation may be missing updates to the bidirectionality constraint, network node constraint, and node capacity constraint?

Good catch; I updated the documentation on my latest commit. Note that RNA has been removed from the bi-directionality constraints in the code, but RNA did not appear explicitly in the documentation of those constraints. So I didn't have to change the documentation of the bi-directionality constraints.

**Review by melody-shellman — APPROVED** [review]
Looks good! I tested the code using input file from main and new input file here that removed RNA arcs. I also tested both configurations for pipeline build (capacity_based and distance_based) and got consistent when comparing runs with different input files. 

One note: can we change the name of this PR to be more descriptive? Maybe "Pipeline Expansion Cost Revision" ? This makes my life easier when I go to write release notes. Can we also add a bullet to the description to mention the two constraints we specifically edited?

**Comment by tarnold17** [comment]
> One note: can we change the name of this PR to be more descriptive? Maybe "Pipeline Expansion Cost Revision" ? This makes my life easier when I go to write release notes. Can we also add a bullet to the description to mention the two constraints we specifically edited?

Done!

**Review by ElmiraShamlou — APPROVED** [review]
looks good

**Pull request merged**
