### PR TITLE
Preload completion tanks

### PR DESCRIPTION
**Pull request by Andresj89**
## Summary
This PR adds support to the operational model for preloading completion tanks.

### Changes
- A binary variable is added `model.vb_z_PadStorage`
- Parameter `model.p_sigma_PadStorage` is now indexed by time
- A new parameter is added `model.p_pi_PadStorage`
- A new rule is included to calculate the cost for preloading tanks. The objective function has been updated accordingly.

### CODE REVIEW

**Review by drouvenm — APPROVED** [review]
LGTM

**Review by MAZamarripa — APPROVED** [review]
looks good.

**Review by MAZamarripa — COMMENTED** [review]
can we add the total fresh water used rule in this PR? @Andresj89

**Review by MAZamarripa — APPROVED** [review]
works good !

**Review by drouvenm — APPROVED** [review]

**Pull request merged**
