### PR TITLE
Enable rendering Unicode characters in ReadTheDocs PDF builds

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Changes proposed in this PR:

- Change LaTeX render engine used by Sphinx to one that supports Unicode characters

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
Note for reviewers: the RTD build passes (i.e. these changes don't break anything), but to see if this actually resolves the PDF build issues we might have to merge it first since non-HTML builds are not generated on PRs because of a (fully understandable) limitation in RTD's service: https://docs.readthedocs.io/en/stable/pull-requests.html#limitations

**Comment by ksbeattie** [comment]
> Note for reviewers: the RTD build passes (i.e. these changes don't break anything), but to see if this actually resolves the PDF build issues we might have to merge it first since non-HTML builds are not generated on PRs because of a (fully understandable) limitation in RTD's service: https://docs.readthedocs.io/en/stable/pull-requests.html#limitations

@lbianchi-lbl: Do you know if there is a set of packages that can be installed (via either pip or conda) to build the PDF locally?  I got as far as

    conda install -c conda-forge texlive-core

on my Mac laptop, but that wasn't enough.

**Comment by lbianchi-lbl** [comment]
@ksbeattie what command are you using to build the PDF locally? I might have the LaTeX stack installed so I can try on my end. Note that, even if I manage to build the PDF successfully, this won't ensure that the same will happen on RTD (because of different LaTeX packages installed there, etc).

**Comment by lbianchi-lbl** [comment]
@ksbeattie I've managed to build something using `make latexpdf` (there are some LaTeX errors, but an openable PDF file is generated), and I think the fix works.

With `latex_engine = "xelatex"`, the characters are rendered (see also the complete file [pareto.pdf](https://github.com/project-pareto/project-pareto/files/8856713/pareto.pdf)):

image

With `latex_engine = "pdflatex"` (the default), I get an error because of the `∈` Unicode character:

image

**Comment by tarnold17** [comment]
> @ksbeattie I've managed to build something using `make latexpdf` (there are some LaTeX errors, but an openable PDF file is generated), and I think the fix works.
> 
> With `latex_engine = "xelatex"`, the characters are rendered (see also the complete file [pareto.pdf](https://github.com/project-pareto/project-pareto/files/8856713/pareto.pdf)):
> 
> image
> 
> With `latex_engine = "pdflatex"` (the default), I get an error because of the `∈` Unicode character:
> 
> image

@lbianchi-lbl - in the pdf you attached, the "is an element of" and summation characters are rendered correctly, but there are some other major issues. Namely, Greek letters are not rendering, and the table of contents is not rendered on the "CONTENTS" page.

**Comment by lbianchi-lbl** [comment]
@tarnold17 Thanks for spotting that, I hadn't realized.

After an atrociously long fight with LaTeX, it seems that I managed to find the magic configuration that results in a (at least to my eyes) usable PDF: [pareto.pdf](https://github.com/project-pareto/project-pareto/files/8865533/pareto.pdf); please go ahead and verify.

I've also added a small Dockerfile and README with instructions on how to test the PDF build locally using Docker. This is based on the official Sphinx Docker image and therefore the closest I managed to get to running the PDF build before merging in this PR.

**Review by tarnold17 — DISMISSED** [review]

**Comment by tarnold17** [comment]
The documentation looks mostly good, but the indices for summations are not formatted correctly, e.g.:

image

**Comment by tarnold17** [comment]
The changes look good to me, but I am wondering if the changes from #140 could also be included here, and merged together in one PR. If you close these two PRs one at a time I think you would have to deal with some annoying merge conflicts.

**Comment by lbianchi-lbl** [comment]
> The changes look good to me, but I am wondering if the changes from #140 could also be included here, and merged together in one PR. If you close these two PRs one at a time I think you would have to deal with some annoying merge conflicts.

@tarnold17 I see your point, and I think that the concern about possible conflicts is valid. In this particular case, I would anyway be inclined towards merging the two PRs separately, and in particular merging this one now and #140 later, considering that:

- We are fairly confident that the changes in this PR didn't substantially alter the formulas since, apart from the summation symbols, all existing symbols were left in place
- The opposite is true for #140: at least from my point of view, basically every formula has been modified by the Unicode -> LaTeX conversion. I don't have a lot of confidence that this process was applied "losslessly" by my hacked-together script, and so the only way I can think of being sure is for someone to review the formulas one by one (ideally, this person would have enough domain knowledge to be able to spot differences at the mathematical level in addition to the typographical level)
- Finally, since I used a script to implement #140, I'm not too concerned about merge conflicts since in the worst case I can simply re-run the script on a fresh checkout instead of fixing the individual conflicts manually

Summary: I propose to merge this PR in to trigger the ReadTheDocs PDF build, so that we can verify that everything looks OK in the RTD-generated document as well.

**Comment by tarnold17** [comment]
@lbianchi-lbl All that seems reasonable to me.

**Review by tarnold17 — APPROVED** [review]

**Pull request merged**
