### PR TITLE
Strategic model - add convert default value for p_pi_Trucking from user units to model units

### LINKED ISSUE #182: Strategic model - add pyunits.convert_value() in default value for p_pi_Trucking parameter
The default value of the trucking hourly cost parameter, `p_pi_Trucking`, is missing a call to `pyunits.convert_value()` to convert from user units to model units.

### PR DESCRIPTION
**Pull request by tarnold17**
## Fixes/Addresses/Summary/Motivation:

In the strategic model, added a call to `pyunits.convert_value` to convert the default value for trucking hourly cost (`p_pi_Trucking`) from user units to model units.

Resolves #182 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Review by melody-shellman — CHANGES_REQUESTED** [review]
Looks good! This was a good catch.  looking at some of our other parameter default values, it looks like these may need correction as well:

- [ ] model.p_lambda_Pipeline
- [ ] model.p_pi_Disposal
- [ ] model.p_pi_Reuse
- [ ] model.p_pi_Sourcing

Can we apply the same correction to these parameters, as well?

**Comment by tarnold17** [comment]
> Looks good! This was a good catch. looking at some of our other parameter default values, it looks like these may need correction as well:
> 
> * [ ]  model.p_lambda_Pipeline
> * [ ]  model.p_pi_Disposal
> * [ ]  model.p_pi_Reuse
> * [ ]  model.p_pi_Sourcing
> 
> Can we apply the same correction to these parameters, as well?

@melody-shellman the four parameters listed here already have the default values converted from user units to model units. For example, the default value for `p_lambda_Pipeline` is `max(PipelineExpansionDistance_convert_to_model.values()) * 100`, where `PipelineExpansionDistance_convert_to_model` is constructed using a dictionary comprehension to  convert all of the popeline expansion distances from user units to model units.

**Comment by melody-shellman** [comment]
Oh I see! Good point. Agreed  that the parameters I listed no longer need adjustment.

One suggestion instead, is it possible to have the formats for `p_pi_Trucking` match that of those I listed for consistency? More specifically, can we create the TruckingHourlyTrucking_convert_to_model dictionary that applies the conversion? With this dictionary, we can call the max without conversion function and we can initialize with this dictionary instead of a conversion.

**Comment by tarnold17** [comment]
> Oh I see! Good point. Agreed that the parameters I listed no longer need adjustment.
> 
> One suggestion instead, is it possible to have the formats for `p_pi_Trucking` match that of those I listed for consistency? More specifically, can we create the TruckingHourlyTrucking_convert_to_model dictionary that applies the conversion? With this dictionary, we can call the max without conversion function and we can initialize with this dictionary instead of a conversion.

@melody-shellman no problem - addressed in latest commit.

**Review by melody-shellman — APPROVED** [review]
Looks good! Results are the same as main for treatment demo case, which is reasonable.

**Review by ElmiraShamlou — APPROVED** [review]
Looks good.

**Pull request merged**
