### PR TITLE
Adding plot_sankey()

### PR DESCRIPTION
**Pull request by Andresj89**
## Summary

This PR adds support for plotting Sankey Diagrams. A test file is included that shows how to use the method. Documentation is in the works.

### CODE REVIEW

**Review by drouvenm — DISMISSED** [review]
LGTM

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Review by MAZamarripa — CHANGES_REQUESTED** [review]
update test

**Review by melody-shellman — DISMISSED** [review]
Approved!

**Review by MAZamarripa — DISMISSED** [review]
lgtm

**Review by melody-shellman — DISMISSED** [review]

**Pull request merged**
